### ISSUE TITLE
怎样实现这样的效果？

### ISSUE THREAD

**Issue by hegelsu** [WhiteDG/ProgressView#2]
就是下载中时中间本来显示百分率的地方显示一个正方的实心四角，暂停时显示一个实心三角，这个怎么弄？

**Comment by WhiteDG** [comment]
目前并没有实现这样的功能，不过你可以调用setTextVisible(false)隐藏进度值，然后在进度条外层套一个FrameLayout，再加上一个居中的ImageView用于显示暂停或加载图标。
