### ISSUE TITLE
设置前缀，原先的进度值还是存在

### ISSUE THREAD

**Issue by JoysWorks** [WhiteDG/ProgressView#4]
我自己设置一个定时器去每秒设置textprefix，结果进度条移动的时候，我设置的textprefix后面还有进度条对应的数值跟在后面！

**Comment by JoysWorks** [comment]
// 绘制文字
    if (mTextVisible) {
      String text = mTextPrefix + getProgress() + mTextSuffix; // 这块能改成自定义text吗？
      float textWidth = mTextPaint.measureText(text);
      float textHeight = (mTextPaint.descent() + mTextPaint.ascent());
      canvas.drawText(text, -textWidth / 2, -textHeight / 2, mTextPaint);
    }

**Comment by WhiteDG** [comment]
mTextPrefix 是进度文本的前缀，你的需求是想自定义整个进度文本吗
